# Generated by Django 4.0.3 on 2022-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='warning',
            field=models.TextField(blank=True),
        ),
    ]
