# Generated by Django 4.0.3 on 2022-05-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_roadmap_detail_alter_roadmap_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.category'),
            preserve_default=False,
        ),
    ]
