# Generated by Django 4.0.3 on 2022-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_quiz_quizquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
