# Generated by Django 4.0.3 on 2022-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_quizquestions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ManyToManyField(to='courses.category'),
        ),
    ]
