# Generated by Django 4.0.3 on 2022-05-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_courses_category_courses_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.category'),
            preserve_default=False,
        ),
    ]
