# Generated by Django 4.0.3 on 2022-05-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
