# Generated by Django 4.0.3 on 2022-05-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_category_parent'),
        ('social', '0014_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='learning_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.courses'),
            preserve_default=False,
        ),
    ]
