# Generated by Django 4.0.3 on 2022-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_post_learning_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='learning_page',
            new_name='learning_environment',
        ),
    ]
