version: "3.9"
   
services:
    welearning:
        build: 
          context: .
          dockerfile: Dockerfile
        container_name: welearning
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
        volumes:
            - .:/usr/src/app
        ports:
            - "80:80"
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0.17
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql-root-password
            MYSQL_DATABASE: mysql-db
        volumes:
            - mysqldata:/var/lib/mysql/data/
        ports:
            - "3308:3306"
volumes:
    mysqldata: